### ISSUE TITLE
IGNORE_NAMES / IGNORE_PATHS does not appear to work

### ISSUE THREAD

**Issue by gjb2048** [moodlehq/moodle-plugin-ci#104]
Hello,

I'm stumped!  Followed: https://github.com/moodlehq/moodle-plugin-ci/blob/master/docs/GHAFileExplained.md and yet the 'Moodle Code Checker' is still checking 'tc_colourpopup.php' and 'tc_colourpopup.js':

![Screenshot 2021-06-01 172150](https://user-images.githubusercontent.com/1058419/120358068-07023900-c2fe-11eb-9ff0-9fb6d3fceab4.png)

As in https://github.com/gjb2048/moodle-format_topcoll/runs/2720540300?check_suite_focus=true.

My yml file is:

https://github.com/gjb2048/moodle-format_topcoll/actions/runs/896709226/workflow#L55-L57
https://github.com/gjb2048/moodle-format_topcoll/actions/runs/896709226/workflow#L82-L84

So I've tried everything I can think of!  Am I missing something or is this a bug?

Travis was / is: https://github.com/gjb2048/moodle-format_topcoll/blob/master/.travis.yml#L31 and that worked.

Really really want to use this :).  And thanks for adding GitHub actions as Travis CI in migrating to dot com is umm, well!!

Thanks,

Gareth

**Comment by kabalin** [comment]
Hello Gareth! Per [docs](https://github.com/moodlehq/moodle-plugin-ci/blob/master/docs/IgnoringFiles.md), if you need to ignore files for specific command, you need to prefix env variable with command, i.e.
```
      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0
        env:
          CODECHECKER_IGNORE_PATHS: 'js'
          CODECHECKER_IGNORE_NAMES: 'tc_colourpopup.php,tc_colourpopup.js'
```

Global ignores should be defined in the step where you run `moodle-plugin-ci install`.
