### ISSUE TITLE
IGNORE_PATHS does not work.

### ISSUE THREAD

**Issue by manojmalik20** [moodlehq/moodle-plugin-ci#133]
Hello!

I am using moodle-plugin-ci in a Moodle plugin and want to ignore some PHPUnit tests from running in the CI. I tried using `IGNORE_PATHS`, `PHPUNIT_IGNORE_PATHS`, `IGNORE_NAMES`, `PHPUNIT_IGNORE_NAMES` but nothing seems to work. I even tried to use these variables in the env for only `phpunit` command instead of defining them while installing `moodle-plugin-ci` but that didn't work also. I am using Github actions and here are some examples I tried in my yml file.

```
- name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          PHPUNIT_IGNORE_PATHS: tests/integration
```

```
- name: PHPUnit tests
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit
        env:
          PHPUNIT_IGNORE_PATHS: tests/integration
          IGNORE_PATHS: tests/integration
```

I've tried several paths too like
```
./moodle/mod/{module_name}/tests/integration/*.php
moodle/mod/{module_name}/tests/integration
plugin/tests/integration
```

But nothing seems to work.
I would really appreciate some help on this.

Thanks,

Manoj
