### ISSUE TITLE
Empty matrix.extensions 

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#234]
The file [test.yaml](https://github.com/moodlehq/moodle-plugin-ci/blob/master/.github/workflows/test.yml#L103C9-L103C19) uses extensions correctly:
    `extensions: pgsql, zip, gd, xmlrpc, soap`
The file[ gha.dist.yml](https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml#L47) is referring to matrix.extensions
`extensions: ${{ matrix.extensions }}`
However, because there are no extensions provided in the [matrix](https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml#L32), the system falls back to the default php extensions:

```
   matrix:
      php: ['7.4', '8.0', '8.1']
      moodle-branch: ['MOODLE_401_STABLE']
      database: [pgsql, mariadb]
```
So the line can be removed or replaced by `extensions:`  This way it will be clear that the tests do not require extra extensions. The chance that someone wants to do all tests with soap and without soap for example, is rather small.

**Comment by stronk7** [comment]
Hi @ewallah,

I'm not sure to understand this issue:

if `${{ matrix.extensions }}` is not defined, then the behaviour of:

``
- name: Setup PHP ${{ matrix.php }}
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ matrix.extensions }}
```

is exactly the same than:

``
- name: Setup PHP ${{ matrix.php }}
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions:
```

The idea is that, if for any reason, a plugin needs some extra extension... then it can be specified in the `${{ matrix.extensions }}` element and it will be automatically used.

So, I'm not sure about what's needed here... maybe some clarification in the `docs/GHAFileExplained.md` file? Or do you think that it would be better to completely delete the `extensions: ${{ matrix.extensions }}` line? Not clear for me...

Ciao :-)

**Comment by ewallah** [comment]
First, extensions are more a variable than part of a matrix. The only case I can imagine where extensions are an array happens  when someone would want to check if an extra extension is needed or not.

Next I find the second sample more exact:
```
- name: Setup PHP ${{ matrix.php }}
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions:
```
Here it is crystal clear that no extra extensions are needed (it shows that the setup-php script already provides all necessary extensions).

**Comment by andrewnicols** [comment]
Hi @ewallah ,

The issue is that some features of PHP start of as extensions and become part of core, or get renamed. They _need_ to be a part of the Matrix to allow different PHP versions to use different extensions.

**Comment by stronk7** [comment]
> The issue is that some features of PHP start of as extensions and become part of core, or get renamed

Yeah, I think that, for example the `php-xmlrpc` is a valid example. It was suggested/required in old Moodle versions, but in Moodle 4.x we removed that requirement (because all the uses were moved from the extension to a library, now part of core).

Because of that... until Moodle 4.x, that extension has to be added if your plugin needs xmlrpc services and, later, it's not needed anymore if you move your plugin away from the extension and switch to the library.

To cover cases like that one (aka, dynamic extension requirements) is when it makes complete sense to have the `${{ matrix.extensions }}` element available in the template.

Of course, if your plugin doesn't need any extra extension, or requires a fixed list of extensions... then the element can be removed or replaced by a fixed list and done.

Ciao :-)

**Comment by ewallah** [comment]
Please show me an example where you could use an array.
Something like 
```
   matrix:
      php: ['8.0',]
      moodle-branch: ['MOODLE_402_STABLE']
      database: ['pgsql', 'mariadb'] 
      extensions:['php-xmlrpc','php-curl']
```
where 4 tests will be running, 2 with the php-xmlrpc extension and 2 with the php-curl extension.

Just because the extensions are mostly multiple values separated by a comma (pgsql, zip, gd, xmlrpc, soap) I find it more clearer to use a environment variable:

```
   env:
      extensions: php-xmlrpc, php-curl
   matrix:
      php: ['8.0',]
      moodle-branch: ['MOODLE_402_STABLE']
      database: ['pgsql', 'mariadb'] 
```

**Comment by stronk7** [comment]
> Please show me an example where you could use an array...

But... who is talking about an array of extensions? We are within a matrix and, generally, individual values are used when within it. For example:

```
matrix:
  - php: 8.0
    moodle-branch: MOODLE_400_STABLE
    database: pgsql
    extensions: xmlrpc, gd, another, ....
  - php: 8.0
    moodle-branch: MOODLE_401_STABLE
    database: pgsql
    extensions: gd, another, ....
```
So, MOODLE_400_STABLE needs the xmlrpc extension (and maybe others) and MOODLE_401_STABLE does not need it anymore (because we replaced it with a library). Just an example.

[Link to the GH Action showing how extensions work](https://github.com/marketplace/actions/setup-php-action#heavy_plus_sign-php-extension-support)
