### ISSUE TITLE
Document `.moodle-plugin-ci.yml`

### ISSUE THREAD

**Issue by NoelDeMartin** [moodlehq/moodle-plugin-ci#257]
I was trying to ignore some files running the `codechecker` command, and eventually I found I could do it by adding the following `.moodle-plugin-ci.yml` file to my plugin:

```yml
filter-phpcs:
  notPaths:
    - tests/vendor/
```

However, I could only discover this by looking at the source code, this `.moodle-plugin-ci.yml` file is not documented anywhere. It seems like it's used at least in 7 places, so it'd be useful to document it.
