### ISSUE TITLE
Recommend a setup method for CI that only needs to be done once and never maintained or updated

### ISSUE THREAD

**Issue by fulldecent** [moodlehq/moodle-plugin-ci#323]
Current documentation says to

> Copy [gha.dist.yml](https://github.com/moodlehq/moodle-plugin-ci/blob/main/gha.dist.yml) file to .github/workflows directory in your project.

This is not DRY and it can lead to outdated flow. For example, this file supports old PHP versions, which should be removed. If you had copied that file in your plugin then your workflow is years outdated, and will continue to be years outdated until somebody on the team randomly thinks to compare that copy-pasta with upstream.

Please study and implement this approach as a primary or a secondary recommendation along with that

https://github.com/catalyst/catalyst-moodle-workflows?tab=readme-ov-file#add-the-workflow

**Comment by gjb2048** [comment]
@fulldecent In the example you've given it states Moodle 3.5, https://github.com/catalyst/catalyst-moodle-workflows?tab=readme-ov-file#configure-support-range, which is even older than the one stated on #322 (Moodle 3.8.3) - so I don't get what you're getting at by these issues.

**Comment by gjb2048** [comment]
Also https://github.com/catalyst/catalyst-moodle-workflows/blob/main/.github/actions/matrix/matrix_includes.yml goes as far back as M3.3!

**Comment by fulldecent** [comment]
The versions of Moodle that are supported is a separate issue. And Catalyst is not cited as best practice here.

Sorry, you are right, PHP 7.4 must be supported.

But in terms of install method, the approach that Catalyst is using is DRY and could be considered best practice:

```yaml
# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    # Required if you plan to publish (uncomment the below)
    # secrets:
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      # Any further options in this section
```


because that would allow the CI to always the recommended version that Moodle HQ has published.
