### ISSUE TITLE
Design reusable GitHub Action for moodle-plugin-ci

### ISSUE THREAD

**Issue by kabalin** [moodlehq/moodle-plugin-ci#53]
Consider creating a dedicated [Action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions) for `moodle-plugin-ci`, and list it in the marketplace (good example [PHP Action](https://github.com/marketplace/actions/setup-php-action)), so that developer who want to enable CI for their plugin would only need to create workflow similar to:
```
name: Moodle Plugin CI

on: [ push, pull_request ]

jobs:
  pluginci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
        database: ['pgsql', 'mariadb']
        moodle-version: ['MOODLE_39_STABLE', 'MOODLE_310_STABLE', 'master']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        # Clone in plugin subdir, so we can setup CI in default directory.
        path: plugin

    - name: Setup moodle-plugin-ci
      uses: moodlehq/moodle-plugin-ci@v3
      with:
          database: ${{ matrix.database }}
          branch: ${{ matrix.moodle-version }}
          pluginpath: ./plugin

    - name: Run Integration tests
      run: |
        moodle-plugin-ci phplint
        moodle-plugin-ci phpcpd
        ....
```
