### ISSUE TITLE
Code coverage and github workflows

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-plugin-ci#59]
With github workflows, the code coverage upload to coveralls does not work out of the box.

A possible solution is to use a secret COVERALLS_REPO_TOKEN (the value can be found in your coveralls.io settings page).

```
      - name: phpunit 
        run: moodle-plugin-ci phpunit --coverage-text --coverage-clover

      - name: coveralls
        env:
          COVERALLS_RUN_LOCALLY: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: moodle-plugin-ci coveralls-upload
        if: matrix.moodle-branch == 'master'
```
[Output:](https://github.com/ewallah/moodle-report_comments/runs/1566168504?check_suite_focus=true#step:22:1)

```
Run moodle-plugin-ci coveralls-upload
  moodle-plugin-ci coveralls-upload
  shell: /bin/bash -e {0}
  env:
    DB: pgsql
    COVERALLS_RUN_LOCALLY: true
    COVERALLS_REPO_TOKEN: ***
Load coverage clover log:
  - /home/runner/work/moodle-report_comments/moodle-report_comments/moodle/report/comments/build/logs/clover.xml
Found 8 source files:
  - 100.00% classes/event/report_viewed.php
  - 100.00% classes/observer.php
  - 100.00% classes/privacy/provider.php
  - 100.00% classes/usertable.php
  - 100.00% db/events.php
  -  29.11% index.php
  - 100.00% lib.php
  -  97.18% locallib.php
Coverage:  78.20% (208/266)
Collect git info
Read environment variables
Dump submitting json file: /home/runner/work/moodle-report_comments/moodle-report_comments/moodle/report/comments/build/logs/coveralls-upload.json
File size: 35.77 kB
Submitting to https://coveralls.io/api/v1/jobs
Finish submitting. status: 200 OK
Accepted Job ##31.1
You can see the build on https://coveralls.io/jobs/72353298
elapsed time: 0.671 sec memory: 6.00 MB

```
![Tests](https://github.com/ewallah/moodle-report_comments/workflows/Tests/badge.svg)
[![Coverage Status](https://coveralls.io/repos/github/ewallah/moodle-report_comments/badge.svg?branch=main)](https://coveralls.io/github/ewallah/moodle-report_comments?branch=main)

**Comment by adpe** [comment]
Hey @ewallah 

I think it would be better if Moodle Plugin CI would support the GitHub Action from the marketplace (https://github.com/marketplace/actions/coveralls-github-action).

Right now I used your approach, but slightly different, so that the upload will only be once:

```yml
- name: Coveralls upload
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      if: ${{ matrix.php == '7.2' && matrix.moodle-branch == 'MOODLE_310_STABLE' && matrix.database == 'mariadb'}}
      run: moodle-plugin-ci coveralls-upload
```

Greets
Adrian
