### ISSUE TITLE
How to release a plugin in a zip format using Github Actions?

### ISSUE THREAD

**Issue by TyDraniu** [moodlehq/moodle-plugin-ci#65]
I've got the following code, but it produces a zip with a wrong structure, it omits the enclosing (top) directory.
```

name: Create Archive
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release Folder
      run:  rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./moodle-plugin
    - name: Switch to Release Folder
      run: cd moodle-plugin
    - uses: actions/checkout@master
    - name: Switch back
      run: cd ..
    - name: Archive Release
      run: zip -r moodle-plugin.zip . -x ".git/*" ".github/*"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'moodle-plugin.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: master
        tag: v1.0.${{ github.run_number }}
```

How to create a moodle plugin in a proper zip format?
